### ISSUE TITLE
大胸dei，起来更新啦

### ISSUE THREAD

**Issue by hhls** [Nyaasu66/CSDN-Beautify#6]

**Comment by Nyaasu66** [comment]
还能用呀，为啥要更新？

**Comment by hhls** [comment]
![image](https://user-images.githubusercontent.com/23031435/61231752-51588c00-a75f-11e9-95b5-694be8878ca0.png)
好吧，我印象中右边的也能去掉，现在底部ad有点点烦人，何不干他一炮？

**Comment by Nyaasu66** [comment]
已更新，广告已被消灭

**Comment by hhls** [comment]
biu特否

**Comment by hhls** [comment]
![image](https://user-images.githubusercontent.com/23031435/61479654-d7c2d700-a9c6-11e9-8b8b-74fde1492886.png)

**Comment by hhls** [comment]
貌似下面的ad还没清除掉大兄弟~
